### ISSUE TITLE
Incorrect processing of string literal with double backslash

### ISSUE THREAD

**Issue by wo1f** [jleffler/scc-snapshots#2]
Hello, I found an example that is not handled correctly.

```cpp
1,2c1,2
< string str_l = "RC-21\\\\M2"s;
< string str = "\"\\r\\n\t\\\"\\\\\"";
---
> string str_l = "RC-21\\\\2"s;
> string str = "\"\\\\\t\\\"\\\\\"";

```
```
SCC Version 8.0.1
cmd: scc -S C++17 -n -e
```

**Comment by jleffler** [comment]
Yes — that too was a bug in the string handling (it also affected single quoted multi-character constants, which aren't a particularly good idea in the first place, being non-portable).  It is fixed in version 8.0.2.
